name: Kubescape

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Set Kubescape Path
        run: echo 'PATH=$PATH:$HOME/.kubescape/bin' >> $GITHUB_ENV

      - name: List Kubescape Directory
        run: ls -al $HOME/.kubescape/bin

      - name: List YAML Files
        run: ls -al *.yaml

      - name: Scan YAML Files
        run: kubescape scan framework nsa *.yaml
